# Generated by Django 5.2.8 on 2025-12-09 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_quiz_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='ai_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='quizzes.aimodel'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(choices=[('tech', 'Programming/Technology'), ('general', 'General Knowledge')], default='tech', max_length=20),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='language',
            field=models.CharField(help_text='Language/subject for the quiz', max_length=50),
        ),
    ]
