# Generated by Django 5.2.8 on 2025-12-12 04:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_quiz_ai_model_quiz_quiz_type_alter_quiz_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.AlterModelOptions(
            name='aimodel',
            options={'verbose_name': 'AI Model', 'verbose_name_plural': 'AI Models'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together={('quiz', 'question')},
        ),
        migrations.AddIndex(
            model_name='option',
            index=models.Index(fields=['question', 'is_correct'], name='quizzes_opt_questio_a33f10_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['quiz'], name='quizzes_que_quiz_id_ffb3fb_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['quiz_type'], name='quizzes_qui_quiz_ty_c4ea4e_idx'),
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['quiz', 'is_correct'], name='quizzes_use_quiz_id_2e6681_idx'),
        ),
    ]
