# Generated by Django 5.2.8 on 2025-12-12 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0006_setup_ai_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_study_mode',
            field=models.BooleanField(default=False, help_text='If True, show correct answer after each question'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='time_taken',
            field=models.PositiveIntegerField(default=0, help_text='Time taken in seconds'),
        ),
    ]
