# Generated by Django 5.2.8 on 2025-12-12 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_add_study_mode_and_timer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='is_study_mode',
        ),
    ]
