# Generated by Django 5.2.8 on 2026-01-02 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0008_remove_is_study_mode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useranswer',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='quiz',
            name='xp_awarded',
            field=models.BooleanField(default=False, help_text='Whether XP was already awarded for this quiz'),
        ),
    ]
